In [2]:
from sklearn.neighbors import BallTree
import numpy as np
np.random.seed(0)
X = np.random.random((10, 3))  # 10 points in 3 dimensions
tree = BallTree(X, leaf_size=2)              
dist, ind = tree.query([X[0]], k=3)                
print(ind)  # indices of 3 closest neighbors
print(dist)  # distances to 3 closest neighbors

[[0 3 1]]
[[0.         0.19662693 0.29473397]]


In [12]:
print(tree.query_radius(X[0], r=0.3, count_only=True))
# ind = tree.query_radius(X[0], r=0.3)
# print(ind)  # indices of neighbors within distance 0.3

[5]


/anaconda/lib/python3.6/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


In [11]:
X = np.random.random((100, 3))
tree = BallTree(X)
tree.kernel_density(X[:3], h=0.1, kernel='gaussian')

array([100.81078326, 137.2280948 , 203.37455824])

In [10]:
X[0]

array([0.26455561, 0.77423369, 0.45615033])